architecture: standalone   # dev usually doesn’t need HA

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: false   # don’t persist in dev
    storageClass: ""
    size: 1Gi

replica:
  replicaCount: 0   # no replicas in dev
  persistence:
    enabled: false
    storageClass: ""
    size: 1Gi

tls:
  enabled: false

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
