apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/DEL-ORG/valdes-argo-k.git
    targetRevision: main
    path: platform-tools/goldilocks/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: goldilocks
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true


