apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: redis
    releaseName: redis-cluster
    repo: https://charts.bitnami.com/bitnami
    namespace: redis-cluster
    valuesFile: values-prod.yaml
