apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: redis
    releaseName: redis-cluster
    namespace: redis-cluster
    version: 18.16.0   
    repo: https://charts.bitnami.com/bitnami
    valuesFile: values-prod.yaml

resources:
  - ../../base
