apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis
resources:
  - ../../base

helmCharts:
  - name: redis
    releaseName: redis
    namespace: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.2.0
    valuesFile: values-prod.yaml
