# values-prod.yaml
architecture: replication

image:
  registry: docker.io
  repository: redis
  tag: 7.4.1 # official Redis image (publicly pullable)

auth:
  enabled: true
  password: "redisStrongPassword123"

master:
  persistence:
    enabled: true
    size: 2Gi

replica:
  replicaCount: 2
  persistence:
    enabled: true
    size: 2Gi

tls:
  enabled: false # disable TLS to start

service:
  type: ClusterIP
  headless:
    enabled: true
    name: redis-headless
