# image:
#   registry: docker.io
#   repository: redis
#   tag: 7.2.4
#   pullPolicy: IfNotPresent


architecture: cluster

cluster:
  nodes: 3
  replicas: 3
  update:
    type: RollingUpdate

persistence:
  size: 2Gi
  storageClass: default

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

networkPolicy:
  enabled: false
  allowExternal: false

tls:
  enabled: false   # Set true once cert secrets exist

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
