architecture: replication
cluster:
  nodes: 6
  replicas: 1

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

persistence:
  enabled: true
  storageClass: gp2
  size: 10Gi

tls:
  enabled: false   # flip to true if you want TLS

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
