architecture: cluster

cluster:
  enabled: true
  nodes: 3       # ✅ 3 masters (shards)
  replicas: 1    # ✅ 1 replica per master


auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    storageClass: default
    size: 1Gi

replica:
  # replicaCount: 3
  persistence:
    enabled: true
    storageClass: default
    size: 1Gi

persistence:
  enabled: true
  size: 1Gi

tls:
  enabled: false   # flip to true if you want TLS

metrics:
  enabled: false
  serviceMonitor:
    enabled: false


# architecture: cluster

# cluster:
#   enabled: true
#   nodes: 2        # number of masters (shards)
#   replicas: 1     # number of replicas per master

# auth:
#   enabled: true
#   existingSecret: redis-secret
#   existingSecretPasswordKey: redis-password

# master:
#   persistence:
#     enabled: true
#     storageClass: default
#     size: 2Gi

# replica:
#   persistence:
#     enabled: true
#     storageClass: default
#     size: 2Gi

# tls:
#   enabled: false   # flip to true if you want TLS

# metrics:
#   enabled: false
#   serviceMonitor:
#     enabled: false
