architecture: cluster

cluster:
  nodes: 3
  replicas: 1
  update:
    type: RollingUpdate

persistence:
  size: 2Gi
  storageClass: default

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1Gi

networkPolicy:
  enabled: true
  allowExternal: false

tls:
  enabled: false   # Set true once cert secrets exist

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
