architecture: replication


image:
  tag: 7.4.1-debian-12-r0

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    storageClass: default
    size: 2Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    storageClass: default
    size: 2Gi

tls:
  enabled: false   

metrics:
  enabled: false
  serviceMonitor:
    enabled: false