replica:
  replicaCount: 3

sentinel:
  replicas: 5

resources:
  master:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
  replica:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
