architecture: replication

auth:
  enabled: true
  existingSecret: redis-secret
  existingSecretPasswordKey: redis-password

master:
  persistence:
    enabled: true
    storageClass: azurefile
    size: 2Gi

replica:
  replicaCount: 1
  persistence:
    enabled: true
    storageClass: azurefile
    size: 2Gi

tls:
  enabled: false   # flip to true if you want TLS

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
