apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster-prod
  namespace: argocd
spec:
  project: platform-tools
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-cluster
  source:
    repoURL: https://charts.bitnami.com/bitnami
    # targetRevision: main
    path: redis-cluster/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

