apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goldilocks

resources:
  - ../../base

helmCharts:
  - name: goldilocks
    repo: https://charts.fairwinds.com/stable
    version: 8.0.2
    releaseName: goldilocks
    namespace: goldilocks
    valuesFiles:
      - ../../base/values.yaml
      - values-dev.yaml


