apiVersion: v1
kind: ServiceAccount
metadata:
  name: lb-cleaner
  namespace: {{ .Values.namespace.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lb-cleaner-role
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lb-cleaner-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: lb-cleaner-role
subjects:
  - kind: ServiceAccount
    name: lb-cleaner
    namespace: {{ .Values.namespace.name }}
