apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

helmCharts:
  - name: cleanup-loadbalancer
    chartName: ../../../
    releaseName: cleanup-loadbalancer
    namespace: cleanup-loadbalancer
    valuesFile: ../../../dev-values.yaml
