controller:
  enabled: true
  rbac:
    create: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 256Mi

dashboard:
  enabled: true
  replicaCount: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false   # overridden per env
