image:
  repository: docker.io/library/redis
  tag: "7.2.0"
  pullPolicy: IfNotPresent

auth:
  enabled: true
  existingSecret: redis-auth
  existingSecretKey: redis-password

persistence:
  enabled: true
  storageClass: default  # or "ebs-encrypted-sc"
  size: 2Gi

replica:
  replicaCount: 2

resources:
  master:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  replica:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"

sentinel:
  enabled: true
  replicas: 3

haproxy:
  enabled: true
  service:
    type: ClusterIP

networkPolicy:
  enabled: true
  allowFromNamespaces:
    - platform-apps

metrics:
  enabled: true
  exporter:
    enabled: true
    serviceMonitor:
      enabled: true
