apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - redis-secret.yaml
  - networkpolicy.yaml

helmCharts:
  - name: redis
    repo: https://charts.bitnami.com/bitnami
    version: 20.2.1
    releaseName: redis-cluster
    namespace: redis-cluster
    valuesFile: values.yaml

