apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-cluster-access
  namespace: redis-cluster
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              access-to-redis: "true"
      ports:
        - protocol: TCP
          port: 6379
  egress:
    - {}
