apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-allow-platform-apps
  namespace: redis-cluster
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              access-to-redis: "true"
  policyTypes:
    - Ingress
