architecture: cluster

auth:
  enabled: true
  existingSecret: redis-password

cluster:
  enabled: true
  nodes: 3
  replicas: 1
  update:
    type: RollingUpdate

service:
  type: ClusterIP
  ports:
    redis: 6379

persistence:
  enabled: true
  size: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClass: gp2-encrypted

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

networkPolicy:
  enabled: true
  allowExternal: false

tls:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: false

