architecture: cluster

auth:
  enabled: true
  existingSecret: redis-password

cluster:
  enabled: true
  slaveCount: 1
  replicas: 1
  nodes: 3
  update:
    type: RollingUpdate

persistence:
  enabled: true
  size: 2Gi
  storageClass: default
  accessModes:
    - ReadWriteOnce

service:
  type: ClusterIP
  clusterIP: None
  ports:
    redis: 6379

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

tls:
  enabled: false

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

