# Use standalone Redis (official image)
architecture: standalone

image:
  repository: redis
  tag: 7.4.1
  pullPolicy: IfNotPresent

# Official Redis image entrypoint and args
command:
  - "redis-server"
args:
  - "--appendonly"
  - "yes"

auth:
  enabled: false  # disable Bitnami-style auth (not supported in official image)

# Disable Bitnami cluster logic (official Redis image doesn't have cluster scripts)
cluster:
  enabled: false

service:
  type: ClusterIP
  ports:
    redis: 6379

persistence:
  enabled: true
  size: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClass: default

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

networkPolicy:
  enabled: true
  allowExternal: false

tls:
  enabled: false

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

