apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-cluster
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 19.0.1   # ✅ pick a stable version
    helm:
      releaseName: redis-cluster
      values: |
        architecture: cluster
        cluster:
          nodes: 6  # 3 masters + 3 replicas
        auth:
          enabled: true
          password: redispassword  # ✅ change to secret in real setup
        persistence:
          enabled: true
          size: 8Gi
        networkPolicy:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
