architecture: cluster

image:
  repository: redis
  tag: 7.4.1


auth:
  enabled: true
  existingSecret: redis-password
  

cluster:
  enabled: true
  nodes: 3
  replicas: 3
  update:
    type: RollingUpdate

service:
  type: ClusterIP
  ports:
    redis: 6379

persistence:
  enabled: true
  size: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClass: default

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

networkPolicy:
  enabled: true
  allowExternal: false

tls:
  enabled: false

metrics:
  enabled: false 
  serviceMonitor:
    enabled: false


