architecture: cluster

auth:
  enabled: true
  existingSecret: redis-password
  existingSecretPasswordKey: redis-password

cluster:
  nodes: 6
  replicas: 1

master:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: encrypted-sc

replica:
  persistence:
    enabled: true
    size: 1Gi
    storageClass: encrypted-sc

service:
  type: ClusterIP
  headless:
    annotations: {}

networkPolicy:
  enabled: true
  allowExternal: false

tls:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
