apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goldilocks
  namespace: argocd
spec:
  project: platform-tools
  source:
    repoURL: https://github.com/your-org/new-pipeline.git
    targetRevision: main
    path: goldilocks/overlays/prod   # choose env
  destination:
    server: https://kubernetes.default.svc
    namespace: goldilocks
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
