apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goldilocks

resources:
  - namespace.yaml

helmCharts:
  - name: goldilocks
    repo: https://charts.fairwinds.com/stable
    version: 8.0.2   # pin to a stable version
    releaseName: goldilocks
    namespace: goldilocks
    valuesFile: values.yaml
