apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: disallow-stringdata-secrets
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: deny-stringdata
    match:
      resources:
        kinds:
        - Secret
    preconditions:
      - key: "{{request.object.stringData}}"
        operator: NotEquals
        value: null
    validate:
      message: "Creation of Secret with stringData (plaintext) is forbidden. Use 'data' with base64-encoded values."
      deny: {}
