apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  # Approved namespaces for production
  - target:
      kind: ConfigMap
      name: lb-cleaner-config
    patch: |-
      - op: replace
        path: /data/approved-namespaces
        value: "argocd"

  # Change CronJob schedule for production
patches:
  - target:
      kind: CronJob
      name: loadbalancer-cleaner
    patch: |-
      - op: replace
        path: /spec/schedule
        value: "*/2 * * * *"
      - op: replace
        path: /spec/jobTemplate/spec/template/spec/containers/0/env/0/value
        value: "false"
